# Notebook 2 – Data Inspection

### Number of Rows

In [ ]:
The number of rows in a dataset represents how many records or observations the dataset contains

In Pandas, each row usually represents one observation, such as one student, one customer, one product, or one transaction

For example, in a student dataset:
    
           Student_ID	Name	Age 	Exam_Score

               101	    Ajay	20	        55
               102	    Vijay	21	        88
               103	    Bunny	19	        62
               104	    Raju	22	        95
               105	    Kiran	20	        72

This dataset contains 5 rows, representing 5 students

In [1]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Ajay", "Vijay", "Bunny", "Raju", "Kiran"],
    "Age": [20, 21, 19, 22, 20],
    "Exam_Score": [55, 88, 62, 95, 72]
}

df = pd.DataFrame(data)

df

   Student_ID   Name  Age  Exam_Score
0         101   Ajay   20          55
1         102  Vijay   21          88
2         103  Bunny   19          62
3         104   Raju   22          95
4         105  Kiran   20          72

In [2]:
number_of_rows = len(df)            #Find the number of rows Using len()

print("Number of rows:", number_of_rows)

Number of rows: 5

In [3]:
number_of_rows = df.shape[0]        #Using shape()

print("Number of rows:", number_of_rows)

Number of rows: 5

In [4]:
number_of_rows = df.index.size       #Using Index()

print("Number of rows:", number_of_rows)

Number of rows: 5

### Number of Columns

In [ ]:
he number of columns in a dataset represents how many variables or features are available in the dataset

Each column represents a particular attribute, such as a student's name, age, study hours, or exam score

For example:
    
       Student_ID	Name	Age	 Exam_Score

           101  	Ajay	20	    55
           102	    Vijay	21	    88
           103	    Bunny	19	    62

This dataset contains 4 columns and 3 rows

In [5]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103],
    "Name": ["Ajay", "Vijay", "Bunny"],
    "Age": [20, 21, 19],
    "Exam_Score": [55, 88, 62]
}

df = pd.DataFrame(data)

df

   Student_ID   Name  Age  Exam_Score
0         101   Ajay   20          55
1         102  Vijay   21          88
2         103  Bunny   19          62

In [6]:
number_of_columns = df.shape[1]     #Find the number of column using shape[1]

print("Number of columns:", number_of_columns)

Number of columns: 4

In [7]:
number_of_columns = len(df.columns)                 

print("Number of columns:", number_of_columns)

Number of columns: 4

In [8]:
number_of_columns = df.columns.size

print("Number of columns:", number_of_columns)

Number of columns: 4

### Data Types

In [ ]:
Data types describe the kind of data stored in each column of a dataset.
    In Pandas, understanding data types helps you choose the correct operations, identify data quality problems, and prepare data for machine learning.

For example, a student's age is numerical, a student's name is text, and an exam date is a date/time value

          Student_ID	Name	Age	Study_Hours	Exam_Date	Result
          
                101	    Ravi	20	      2.5	2026-10-01	Fail
                102	    Priya	21        5.0	2026-10-02	Pass
                103	    Arun	19	      3.0	2026-10-03	Fail

In [9]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Ravi", "Priya", "Arun", "Sneha"],
    "Age": [20, 21, 19, 22],
    "Study_Hours": [2.5, 5.0, 3.0, 6.5],
    "Passed": [False, True, False, True],
    "Exam_Date": [
        "2026-10-01",
        "2026-10-02",
        "2026-10-03",
        "2026-10-04"
    ]
}

df = pd.DataFrame(data)

df["Exam_Date"] = pd.to_datetime(df["Exam_Date"])

df

   Student_ID   Name  Age  Study_Hours  Passed  Exam_Date
0         101   Ravi   20          2.5   False 2026-10-01
1         102  Priya   21          5.0    True 2026-10-02
2         103   Arun   19          3.0   False 2026-10-03
3         104  Sneha   22          6.5    True 2026-10-04

In [10]:
print(df.dtypes)

Student_ID              int64
Name                      str
Age                     int64
Study_Hours           float64
Passed                   bool
Exam_Date      datetime64[us]
dtype: object

In [11]:
print(df["Age"].dtype)
print(df["Study_Hours"].dtype)
print(df["Name"].dtype)
print(df["Exam_Date"].dtype)

int64
float64
str
datetime64[us]

In [12]:
df["Age"] = df["Age"].astype("int64")

print(df["Age"].dtype)

int64

### Column Names

In [ ]:
Column names are the labels used to identify each column in a DataFrame. They describe the information stored in each column

For example, in a student dataset, Name, Age, Study_Hours, and Exam_Score are column names

         Name	   Age	Study_Hours 	Exam_Score
          Ravi  	20	2.5	               55
          Priya	    21	5.0	               88
          Arun    	19	3.0                62

Column names help you access, select, rename, and analyze specific variables in a dataset

In [13]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Ajay", "Vijay", "Bunny", "Raju"],
    "Age": [20, 21, 19, 22],
    "Study_Hours": [2.5, 5.0, 3.0, 6.0],
    "Exam_Score": [55, 88, 62, 95]
}

df = pd.DataFrame(data)

df

   Student_ID   Name  Age  Study_Hours  Exam_Score
0         101   Ajay   20          2.5          55
1         102  Vijay   21          5.0          88
2         103  Bunny   19          3.0          62
3         104   Raju   22          6.0          95

In [14]:
print(df.columns)  #Display all column names

Index(['Student_ID', 'Name', 'Age', 'Study_Hours', 'Exam_Score'], dtype='str')

In [15]:
column_names = df.columns.tolist() #Convert column names into a list

print(column_names)

['Student_ID', 'Name', 'Age', 'Study_Hours', 'Exam_Score']

In [16]:
print(df.columns[0])              #Access a Specific Column Name
print(df.columns[1])
print(df.columns[-1])

Student_ID
Name
Exam_Score

In [ ]:
df.columns[0] returns the first column name
df.columns[1] returns the second column name
df.columns[-1] returns the last column name

### Index

In [ ]:
An index in Pandas is used to label and identify the rows of a DataFrame or Series

By default, Pandas assigns an integer index starting from 0. However, you can also use meaningful labels, such as student IDs, dates, or product codes, as an index.

Example:
    
             Index	Student_ID	Name	Age	Exam_Score

                0	101	        Ravi	20	  55

                1	102     	Priya	21	  88

                2	103        	Arun	19	  62

                3	104	        Sneha	22	  95

Here, 0, 1, 2, and 3 are the row index labels

Important: The index is not necessarily a column. It is a separate part of the DataFrame structure

In [17]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Ravi", "Priya", "Arun", "Sneha"],
    "Age": [20, 21, 19, 22],
    "Exam_Score": [55, 88, 62, 95]
}

df = pd.DataFrame(data)

df

   Student_ID   Name  Age  Exam_Score
0         101   Ravi   20          55
1         102  Priya   21          88
2         103   Arun   19          62
3         104  Sneha   22          95

In [18]:
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [ ]:
Explanation:

- start=0: The index begins at 0
- stop=4: The index ends before 4
- step=1: The index increases by 1 each time

### head()

In [ ]:
The head() method in Pandas is used to display the first few rows of a DataFrame or Series.

It is commonly used during data inspection to understand the structure of a dataset, check column names, and 
preview the values after loading a CSV or Excel file

Syntax:

df.head(n)

df — the DataFrame name
head() — displays the first rows
n — the number of rows to display. It is optional
Default value of n is 5

In [19]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Divya", "Rahul"],
    "Age": [20, 21, 19, 22, 20, 21, 23],
    "Study_Hours": [2.5, 5.0, 3.0, 6.0, 4.0, 5.5, 2.0],
    "Exam_Score": [55, 88, 62, 95, 72, 91, 48]
}

df = pd.DataFrame(data)

df

   Student_ID   Name  Age  Study_Hours  Exam_Score
0         101   Ravi   20          2.5          55
1         102  Priya   21          5.0          88
2         103   Arun   19          3.0          62
3         104  Sneha   22          6.0          95
4         105  Kiran   20          4.0          72
5         106  Divya   21          5.5          91
6         107  Rahul   23          2.0          48

In [20]:
df.head()

   Student_ID   Name  Age  Study_Hours  Exam_Score
0         101   Ravi   20          2.5          55
1         102  Priya   21          5.0          88
2         103   Arun   19          3.0          62
3         104  Sneha   22          6.0          95
4         105  Kiran   20          4.0          72

In [ ]:
Explanation: Since we did not specify a number inside head(), Pandas displays the first five rows by default

In [21]:
df.head(3)

   Student_ID   Name  Age  Study_Hours  Exam_Score
0         101   Ravi   20          2.5          55
1         102  Priya   21          5.0          88
2         103   Arun   19          3.0          62

### tail()

In [ ]:
The tail() method in Pandas is used to display the last few rows of a DataFrame or Series

It is useful during data inspection to check the final records, verify that a file loaded correctly, and 
identify unusual values near the end of a dataset

Syntax:

df.tail(n)

df — the DataFrame name
tail() — displays the last rows
n — the number of rows to display; it is optional
The default value of n is 5

In [22]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Divya", "Rahul"],
    "Age": [20, 21, 19, 22, 20, 21, 23],
    "Study_Hours": [2.5, 5.0, 3.0, 6.0, 4.0, 5.5, 2.0],
    "Exam_Score": [55, 88, 62, 95, 72, 91, 48]
}

df = pd.DataFrame(data)

df

   Student_ID   Name  Age  Study_Hours  Exam_Score
0         101   Ravi   20          2.5          55
1         102  Priya   21          5.0          88
2         103   Arun   19          3.0          62
3         104  Sneha   22          6.0          95
4         105  Kiran   20          4.0          72
5         106  Divya   21          5.5          91
6         107  Rahul   23          2.0          48

In [23]:
df.tail()    #To Display last 5 rows

   Student_ID   Name  Age  Study_Hours  Exam_Score
2         103   Arun   19          3.0          62
3         104  Sneha   22          6.0          95
4         105  Kiran   20          4.0          72
5         106  Divya   21          5.5          91
6         107  Rahul   23          2.0          48

In [24]:
df.tail(3)         #To Display Specific no of rows

   Student_ID   Name  Age  Study_Hours  Exam_Score
4         105  Kiran   20          4.0          72
5         106  Divya   21          5.5          91
6         107  Rahul   23          2.0          48

### sample()

In [ ]:
In Pandas, the sample() method is used to select random rows from a DataFrame
It helps us inspect different parts of a dataset without displaying every row

For example, if a dataset contains 1,000 student records, sample() can display 5 randomly selected students.

Why is sample() useful in Data Inspection?

- Inspect random records from a dataset.
- Identify unusual or unexpected values.
- Check whether data appears consistent across different records.
- Quickly examine large datasets.

Syntax:

DataFrame.sample(n=5, random_state=None)


Parameter	        Description

n	              Number of random rows to select. Default is 1

random_state	Controls randomness so the same sample can be reproduced

In [25]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Ravi", "Priya", "Arun", "Sneha",
             "Kiran", "Divya", "Rahul", "Anu"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19],
    "Study_Hours": [3, 5, 2, 6, 4, 7, 3, 5],
    "Exam_Score": [65, 85, 55, 90, 72, 95, 68, 88]
}

df = pd.DataFrame(data)

df

   Student_ID   Name  Age  Study_Hours  Exam_Score
0         101   Ravi   20            3          65
1         102  Priya   21            5          85
2         103   Arun   19            2          55
3         104  Sneha   22            6          90
4         105  Kiran   20            4          72
5         106  Divya   21            7          95
6         107  Rahul   23            3          68
7         108    Anu   19            5          88

In [26]:
df.sample()     #To select one row

   Student_ID   Name  Age  Study_Hours  Exam_Score
1         102  Priya   21            5          85

In [27]:
df.sample(n=3)       #To select 3 rows

   Student_ID   Name  Age  Study_Hours  Exam_Score
7         108    Anu   19            5          88
6         107  Rahul   23            3          68
1         102  Priya   21            5          85

In [28]:
df.sample(n=3, random_state=42)        #Random Sample

   Student_ID   Name  Age  Study_Hours  Exam_Score
1         102  Priya   21            5          85
5         106  Divya   21            7          95
0         101   Ravi   20            3          65

In [29]:
print("Dataset shape:", df.shape)

print("\nRandom 5 rows:")
display(df.sample(n=5, random_state=42))

print("\nRandom 3 rows:")
display(df.sample(n=3, random_state=42))

Dataset shape: (8, 5)

Random 5 rows:

   Student_ID   Name  Age  Study_Hours  Exam_Score
1         102  Priya   21            5          85
5         106  Divya   21            7          95
0         101   Ravi   20            3          65
7         108    Anu   19            5          88
2         103   Arun   19            2          55

Random 3 rows:

   Student_ID   Name  Age  Study_Hours  Exam_Score
1         102  Priya   21            5          85
5         106  Divya   21            7          95
0         101   Ravi   20            3          65

### shape

In [ ]:
In Pandas, the shape attribute returns the number of rows and columns in a DataFrame

It helps us understand the dimensions of a dataset immediately after loading it

For example, if a dataset contains 100 student records and 5 columns, its shape is:
    

Shape = (100, 5)

- 100 represents the number of rows
- 5 represents the number of columns

Important: shape is an attribute, not a method. Therefore, use df.shape, not df.shape()

Syntax:

DataFrame.shape

In [30]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran"],
    "Age": [20, 21, 19, 22, 20],
    "Study_Hours": [3, 5, 2, 6, 4],
    "Exam_Score": [65, 85, 55, 90, 72]
}

df = pd.DataFrame(data)

df

   Student_ID   Name  Age  Study_Hours  Exam_Score
0         101   Ravi   20            3          65
1         102  Priya   21            5          85
2         103   Arun   19            2          55
3         104  Sneha   22            6          90
4         105  Kiran   20            4          72

In [32]:
df.shape     #Find the dataset shape

(5, 5)

In [ ]:
Explanation:

- 5 rows represent five student records
- 5 columns represent Student_ID, Name, Age, Study_Hours, and Exam_Score

In [33]:
df.shape[0]

5

### info()

In [ ]:
In Pandas, the info() method provides a summary of a DataFrame's structure and information

It helps us understand:
    
- Total number of rows and columns
- Column names
- Number of non-null values in each column
- Data types of columns
- Memory usage of the DataFrame
Real-world example: When you load a student dataset containing thousands of records,
info() helps you quickly check whether columns have missing values and whether their data types are appropriate.

Syntax:

DataFrame.info()

In [34]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Ravi", "Priya", "Arun", "Sneha", "Kiran"],
    "Age": [20, 21, None, 22, 20],
    "Study_Hours": [3.5, 5.0, 2.0, None, 4.0],
    "Exam_Score": [65, 85, 55, 90, 72]
}

df = pd.DataFrame(data)

df

   Student_ID   Name   Age  Study_Hours  Exam_Score
0         101   Ravi  20.0          3.5          65
1         102  Priya  21.0          5.0          85
2         103   Arun   NaN          2.0          55
3         104  Sneha  22.0          NaN          90
4         105  Kiran  20.0          4.0          72

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   5 non-null      int64
 1   Name         5 non-null      str
 2   Age          4 non-null      float64
 3   Study_Hours  4 non-null      float64
 4   Exam_Score   5 non-null      int64
dtypes: float64(2), int64(2), str(1)
memory usage: 355.0 bytes

In [36]:
print("Dataset shape:", df.shape)

print("\nDataset information:")
df.info()

print("\nMissing values in each column:")
print(df.isnull().sum())

Dataset shape: (5, 5)

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   5 non-null      int64
 1   Name         5 non-null      str
 2   Age          4 non-null      float64
 3   Study_Hours  4 non-null      float64
 4   Exam_Score   5 non-null      int64
dtypes: float64(2), int64(2), str(1)
memory usage: 355.0 bytes

Missing values in each column:
Student_ID     0
Name           0
Age            1
Study_Hours    1
Exam_Score     0
dtype: int64