# Notebook 9 – Categorical Data Analysis

Categorical data analysis is the process of studying variables that represent groups, labels, or classes

Examples include:

- Gender: Male, Female, Other
- Department: IT, HR, Sales, Finance
- Product_Category: Electronics, Clothing, Furniture
- Payment_Method: Cash, UPI, Card
- Churn: Yes, No — a possible target variable
  
Why is it important?

- Understand the composition of a dataset
- Detect rare or unexpected categories
- Identify imbalanced categories
- Discover relationships between features and the target
- Prepare categorical features for machine learning

### Unique Categories

In [ ]:
Unique categories are the distinct values present in a categorical column of a dataset

For example, suppose a dataset contains a Department column with the following values:
    
Employee	Department

     1	       IT
     2	       HR
     3	       IT
     4	       Sales
     5	       HR

The unique categories are IT, HR, and Sales
- Total observations = 5
- Number of unique categories = 3

Why is it important?

- Understand the different categories in a column
- Detect inconsistent labels and unexpected values

In [3]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Sales", "HR"],
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "Payment_Method": ["UPI", "Cash", "Card", "UPI", "Cash"]
})

df

  Department  Gender Payment_Method
0         IT    Male            UPI
1         HR  Female           Cash
2         IT    Male           Card
3      Sales  Female            UPI
4         HR    Male           Cash

In [4]:
print(df["Department"].unique())    #Find unique categories using unique()

<ArrowStringArray>
['IT', 'HR', 'Sales']
Length: 3, dtype: str

In [6]:
categorical_columns = df.select_dtypes(          #Analyze all categorical columns
    include=["object", "category", "string"]
).columns

for col in categorical_columns:
    print(f"\nColumn: {col}")
    print("Unique Categories:", df[col].unique())
    print("Number of Unique Categories:", df[col].nunique())

Column: Department
Unique Categories: <ArrowStringArray>
['IT', 'HR', 'Sales']
Length: 3, dtype: str
Number of Unique Categories: 3

Column: Gender
Unique Categories: <ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str
Number of Unique Categories: 2

Column: Payment_Method
Unique Categories: <ArrowStringArray>
['UPI', 'Cash', 'Card']
Length: 3, dtype: str
Number of Unique Categories: 3

### Category Frequencies

In [ ]:
Category frequency is the number of times each unique category appears in a categorical column

For example, consider a customer dataset with a Payment_Method column:
    
Payment_Method
    
UPI
Cash
UPI
Card
Cash
UPI

The category frequencies are:
    
Category	Frequency

UPI         	3
Cash        	2
Card	        1

Why is it important?

- Identify the most and least common categories
- Understand customer preferences and business patterns
- Detect rare categories and possible data-quality issues
- Identify imbalanced categorical variables

In [8]:
import pandas as pd

df = pd.DataFrame({
    "Payment_Method": [
        "UPI", "Cash", "UPI",
        "Card", "Cash", "UPI"
    ],
    "Department": [
        "IT", "HR", "IT",
        "Sales", "HR", "IT"
    ]
})

df

  Payment_Method Department
0            UPI         IT
1           Cash         HR
2            UPI         IT
3           Card      Sales
4           Cash         HR
5            UPI         IT

In [9]:
df["Payment_Method"].value_counts()

Payment_Method
UPI     3
Cash    2
Card    1
Name: count, dtype: int64

Interpretation:

- UPI is the most frequent payment method, with 3 observations
- Cash appears 2 times
- Card is the least frequent, with 1 observation
By default, value_counts() sorts categories from highest to lowest frequency and excludes missing values

In [10]:
categorical_columns = df.select_dtypes(                      #Calculate frequencies for all categorical columns
    include=["object", "category", "string"]
).columns

for col in categorical_columns:
    print(f"\nFrequency of {col}:")
    print(df[col].value_counts())

Frequency of Payment_Method:
Payment_Method
UPI     3
Cash    2
Card    1
Name: count, dtype: int64

Frequency of Department:
Department
IT       3
HR       2
Sales    1
Name: count, dtype: int64

### Category Distribution

In [ ]:
Category distribution describes how observations are spread across the different categories of a categorical variable. 
    It is usually expressed as a count or a percentage.

For example, consider a customer dataset containing a Payment_Method column.
        
PaymentMethod	Frequency	Percentage

    UPI	           50	      50%
    Cash	       30	      30%
    Card	       20	      20%
        
   Total	       100	     100%

Interpretation:

- UPI is the most common payment method, representing 50% of customers
- Cash accounts for 30%
- Card accounts for 20%

Why is it important?

- Understand the composition of a dataset
- Identify dominant and less common categories
- Detect uneven category distributions
- Support business decisions and machine learning preprocessing

In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.DataFrame({
    "Payment_Method": [
        "UPI", "Cash", "UPI", "Card", "UPI",
        "Cash", "Card", "UPI", "Cash", "UPI",
        "Card", "Cash", "UPI", "UPI", "Cash"
    ],
    "Department": [
        "IT", "HR", "IT", "Sales", "IT",
        "HR", "Sales", "IT", "HR", "IT",
        "Sales", "HR", "IT", "IT", "HR"
    ]
})

df.head()

  Payment_Method Department
0            UPI         IT
1           Cash         HR
2            UPI         IT
3           Card      Sales
4            UPI         IT

In [12]:
df["Payment_Method"].value_counts()   #Calculate category frequencies

Payment_Method
UPI     7
Cash    5
Card    3
Name: count, dtype: int64

In [13]:
payment_distribution = (         #Calculate category percentages
    df["Payment_Method"]
    .value_counts(normalize=True)
    .mul(100)
)

print(payment_distribution.round(2))

Payment_Method
UPI     46.67
Cash    33.33
Card    20.00
Name: proportion, dtype: float64

In [14]:
categorical_columns = df.select_dtypes(              #Analyze all categorical columns
    include=["object", "category", "string"]
).columns

for col in categorical_columns:
    print(f"\nDistribution of {col}:")

    print(
        (df[col].value_counts(normalize=True) * 100)
        .round(2)
    )

Distribution of Payment_Method:
Payment_Method
UPI     46.67
Cash    33.33
Card    20.00
Name: proportion, dtype: float64

Distribution of Department:
Department
IT       46.67
HR       33.33
Sales    20.00
Name: proportion, dtype: float64

### Rare Categories

In [ ]:
Rare categories are categories that occur very infrequently in a categorical column compared with other categories

For example, consider a dataset containing customer payment methods:

PaymentMethod	Frequency	Percentage

    UPI	          500	       50%
    Cash	      300	       30%
    Card	      190	       19%
    Cheque	      10	        1%

Here, Cheque is a rare category because it represents only 1% of observations

Why is rare category analysis important?

- Identify categories with very few observations
- Detect spelling mistakes and inconsistent labels
- Reduce unnecessary complexity during machine learning preprocessing
- Decide whether rare categories should be retained or grouped into "Other"

Rare categories are not necessarily errors. They may contain valuable information, so investigate them before changing the data

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.DataFrame({
    "Payment_Method": [
        "UPI", "UPI", "UPI", "UPI", "UPI",
        "Cash", "Cash", "Cash",
        "Card", "Card",
        "Cheque"
    ]
})

df

   Payment_Method
0             UPI
1             UPI
2             UPI
3             UPI
4             UPI
5            Cash
6            Cash
7            Cash
8            Card
9            Card
10         Cheque

In [16]:
category_counts = df["Payment_Method"].value_counts()    #Calculate category frequencies

print(category_counts)

Payment_Method
UPI       5
Cash      3
Card      2
Cheque    1
Name: count, dtype: int64

In [18]:
category_percentages = (            #Calculate category percentages
    df["Payment_Method"]
    .value_counts(normalize=True)
    .mul(100)
)

print(category_percentages.round(2))

Payment_Method
UPI       45.45
Cash      27.27
Card      18.18
Cheque     9.09
Name: proportion, dtype: float64

In [19]:
threshold = 15         #Identify rare categories

rare_categories = category_percentages[
    category_percentages < threshold
]

print("Rare Categories:")
print(rare_categories)

Rare Categories:
Payment_Method
Cheque    9.090909
Name: proportion, dtype: float64

In [21]:
threshold = 15                   #Group rare categories into Other

category_percentages = (
    df["Payment_Method"].value_counts(normalize=True) * 100
)

rare = category_percentages[
    category_percentages < threshold
].index

df["Payment_Method_Grouped"] = df["Payment_Method"].where(
    ~df["Payment_Method"].isin(rare),
    "Other"
)

print(df["Payment_Method_Grouped"].value_counts())

Payment_Method_Grouped
UPI      5
Cash     3
Card     2
Other    1
Name: count, dtype: int64

### High Cardinality

In [ ]:
High cardinality refers to a categorical feature that contains a large number of distinct categories

For example, consider a customer dataset:
    
    Customer_ID	    City	     Payment_Method

      C001	     Hyderabad	     UPI
      C002	     Chennai	    Cash
      C003	     Bengaluru	    Card
      C004   	 Hyderabad	    UPI
      C005	     Mumbai	        Cash

- Customer_ID may have a unique value for almost every customer
- City may contain many distinct categories
- Payment_Method usually contains only a few categories

Why is high cardinality important?

- One-hot encoding can create a large number of columns
- Some categories may have very few observations
- Models may overfit to rare categories
- Identifier columns may add complexity without providing useful predictive information

In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.DataFrame({
    "Customer_ID": [
        "C001", "C002", "C003", "C004", "C005",
        "C006", "C007", "C008", "C009", "C010"
    ],
    "City": [
        "Hyderabad", "Chennai", "Mumbai", "Hyderabad",
        "Bengaluru", "Chennai", "Delhi", "Mumbai",
        "Hyderabad", "Pune"
    ],
    "Payment_Method": [
        "UPI", "Cash", "Card", "UPI", "Cash",
        "UPI", "Card", "Cash", "UPI", "UPI"
    ]
})

df.head()

  Customer_ID       City Payment_Method
0        C001  Hyderabad            UPI
1        C002    Chennai           Cash
2        C003     Mumbai           Card
3        C004  Hyderabad            UPI
4        C005  Bengaluru           Cash

In [24]:
categorical_columns = df.select_dtypes(                  #Count unique categories
    include=["object", "category", "string"]
).columns

for col in categorical_columns:
    print(f"{col}: {df[col].nunique()} unique categories")

Customer_ID: 10 unique categories
City: 6 unique categories
Payment_Method: 3 unique categories

Interpretation:

- Customer_ID: 10 unique values in 10 records
- City: 7 unique values
- Payment_Method: 3 unique values

In [25]:
cardinality_ratio = (                                #Calculate the cardinality ratio
    df[categorical_columns].nunique() / len(df)
) * 100

print(cardinality_ratio.round(2))

Customer_ID       100.0
City               60.0
Payment_Method     30.0
dtype: float64

In [26]:
threshold = 5                #Identify high-cardinality columns

for col in categorical_columns:
    unique_count = df[col].nunique()

    if unique_count > threshold:
        print(f"{col}: High cardinality ({unique_count})")
    else:
        print(f"{col}: Low cardinality ({unique_count})")

Customer_ID: High cardinality (10)
City: High cardinality (6)
Payment_Method: Low cardinality (3)

### Low Cardinality

In [ ]:
Low cardinality refers to a categorical feature that contains a relatively small number of distinct categories

For example, consider a customer dataset:
    
Customer	Gender	Payment_Method	Contract_Type

C001	    Male	UPI	    Monthly
C002	    Female	Cash	Yearly
C003	    Male	Card	Monthly
C004	    Female	UPI	    Quarterly
C005	    Male	Cash	Yearly

- Gender has 2 unique categories
- Payment_Method has 3 unique categories
- Contract_Type has 3 unique categories

Why is low cardinality important?

- Makes categorical data easier to analyze
- Simplifies encoding for machine learning
- Helps compare category frequencies and target distributions
- Makes visualizations easier to interpret

In [27]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.DataFrame({
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],
    "Payment_Method": [
        "UPI", "Cash", "Card", "UPI", "Cash",
        "UPI", "Card", "Cash", "UPI", "UPI"
    ],
    "Contract_Type": [
        "Monthly", "Yearly", "Monthly", "Quarterly",
        "Yearly", "Monthly", "Quarterly", "Yearly",
        "Monthly", "Yearly"
    ]
})

df.head()

   Gender Payment_Method Contract_Type
0    Male            UPI       Monthly
1  Female           Cash        Yearly
2    Male           Card       Monthly
3  Female            UPI     Quarterly
4    Male           Cash        Yearly

In [28]:
categorical_columns = df.select_dtypes(                 #Count unique categories
    include=["object", "category", "string"]
).columns

for col in categorical_columns:
    print(f"{col}: {df[col].nunique()} unique categories")

Gender: 2 unique categories
Payment_Method: 3 unique categories
Contract_Type: 3 unique categories

In [29]:
cardinality_ratio = (                       #Calculate the cardinality ratio
    df[categorical_columns].nunique() / len(df)
) * 100

print(cardinality_ratio.round(2))

Gender            20.0
Payment_Method    30.0
Contract_Type     30.0
dtype: float64

In [30]:
threshold = 5                    #Identify low-cardinality columns

for col in categorical_columns:
    unique_count = df[col].nunique()

    if unique_count <= threshold:
        print(f"{col}: Low cardinality ({unique_count})")
    else:
        print(f"{col}: High cardinality ({unique_count})")

Gender: Low cardinality (2)
Payment_Method: Low cardinality (3)
Contract_Type: Low cardinality (3)

In [31]:
for col in categorical_columns:     #Analyze category frequencies
    print(f"\nFrequency of {col}:")
    print(df[col].value_counts())

Frequency of Gender:
Gender
Male      5
Female    5
Name: count, dtype: int64

Frequency of Payment_Method:
Payment_Method
UPI     5
Cash    3
Card    2
Name: count, dtype: int64

Frequency of Contract_Type:
Contract_Type
Monthly      4
Yearly       4
Quarterly    2
Name: count, dtype: int64

### Category Imbalance

In [ ]:
Category imbalance occurs when some categories in a categorical feature contain significantly more observations than others

For example, consider a customer dataset with a Payment_Method column

PaymentMethod	Frequency	Percentage

       UPI	       800	        80%
       Cash        150	        15%
       Card	        50	         5%
           
       Total	   1,000	     100%

Here, UPI dominates the distribution, while Card represents only 5% of observations.

Why is category imbalance important?
    
- Identifies dominant and underrepresented categories
- Helps detect unusual distributions and potential data-quality issues
- Helps businesses understand customer preferences
- Can affect machine learning performance, particularly when the target variable is imbalanced

In [34]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.DataFrame({
    "Payment_Method": (
        ["UPI"] * 16 +
        ["Cash"] * 3 +
        ["Card"] * 1
    )
})

df["Payment_Method"].value_counts()

Payment_Method
UPI     16
Cash     3
Card     1
Name: count, dtype: int64

In [35]:
category_percentage = (                #Calculate category percentages
    df["Payment_Method"]
    .value_counts(normalize=True)
    .mul(100)
)

print(category_percentage.round(2))

Payment_Method
UPI     80.0
Cash    15.0
Card     5.0
Name: proportion, dtype: float64

Interpretation:

- UPI accounts for 80% of observations
- Cash accounts for 15%
- Card accounts for 5%

The distribution is uneven because UPI is much more common than the other payment methods

In [36]:
counts = df["Payment_Method"].value_counts()              #Measure the imbalance ratio

imbalance_ratio = counts.max() / counts.min()

print("Imbalance Ratio:", imbalance_ratio)

Imbalance Ratio: 16.0